language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pandas
  - pip install codecov
# command to run tests
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
